[package]
name = "baba"
version = "0.1.0"
edition = "2021"

[dependencies]
ecolor = "0.28.1"
evenio = "0.6.0"
glam = "0.28.0"
image = "0.25.1"
sdl2 = { version = "0.37.0", features = ["unsafe_textures", "image"] }
sdl2-sys = "0.37.0"
thiserror = "1.0.63"
